= kaocha-nrepl
:toc:
:toc-placement: preamble
:toclevels: 2

// Need some preamble to get TOC:
{empty}

https://github.com/nrepl/nrepl[nREPL] Middleware for https://github.com/lambdaisland/kaocha[kaocha].

image:https://img.shields.io/circleci/project/github/liquidz/kaocha-nrepl/master.svg["CircleCI", link="https://circleci.com/gh/liquidz/kaocha-nrepl"]
image:https://versions.deps.co/liquidz/kaocha-nrepl/status.svg["Dependencies Status", link="https://versions.deps.co/liquidz/kaocha-nrepl"]
image:https://img.shields.io/clojars/v/kaocha-nrepl.svg["Clojars Project", link="https://clojars.org/kaocha-nrepl"]
image:https://img.shields.io/badge/patreon-donate-yellow.svg?logo=Patreon["Become a Patron", link="https://www.patreon.com/uochan"]

== Supported tests

- [x] clojure.test
- [x] https://github.com/marick/Midje[Midje] via https://github.com/lambdaisland/kaocha-midje[kaocha-midje]
- [ ] ClojureScript via https://github.com/lambdaisland/kaocha-cljs[kaocha-cljs]

== Ops

[cols="3*,a"]
|===
| Op name | Required | Optional | Note

| kaocha-test-all
|
| `config-file`, `disable-progress-reporter`
| Run all tests.

| kaocha-test
| `testable-ids`
| `config-file`, `disable-progress-reporter`
| Run tests by `testable-ids`. +
See link:https://cljdoc.org/d/lambdaisland/kaocha/CURRENT/doc/6-focusing-and-skipping#on-id[kaocha document] for `testable-id`.

| kaocha-testable-ids
|
| `config-file`
| Return testable ids.

| kaocha-retest
|
|
| Rerun last failed tests.

|===

== Related projects

- https://github.com/liquidz/vim-iced-kaocha[liquidz/vim-iced-kaocha]

== License

Copyright © 2019 https://twitter.com/uochan[Masashi Iizuka]

This program and the accompanying materials are made available under the
terms of the Eclipse Public License 2.0 which is available at
http://www.eclipse.org/legal/epl-2.0.

This Source Code may also be made available under the following Secondary
Licenses when the conditions for such availability set forth in the Eclipse
Public License, v. 2.0 are satisfied: GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or (at your
option) any later version, with the GNU Classpath Exception which is available
at https://www.gnu.org/software/classpath/license.html.
