= kaocha-nrepl
:toc:
:toc-placement: preamble
:toclevels: 2

// Need some preamble to get TOC:
{empty}

https://github.com/nrepl/nrepl[nREPL] Middleware for https://github.com/lambdaisland/kaocha[kaocha].

== Supported types

* clojure.test
* https://github.com/marick/Midje[Midje] via https://github.com/lambdaisland/kaocha-midje[kaocha-midje]

== Ops

[cols="3*,a"]
|===
| Op name | Required | Optional | Note

| kaocha-test-all
|
| `config-file`
| Run all tests.

| kaocha-test
| `testable-ids`
| `config-file`
| Run tests by `testable-ids`. +
See link:cljdoc.org/d/lambdaisland/kaocha/CURRENT/doc/6-focusing-and-skipping#on-id[kaocha document] for `testable-id`.

|===

== License

Copyright © 2019 https://twitter.com/uochan[Masashi Iizuka]

This program and the accompanying materials are made available under the
terms of the Eclipse Public License 2.0 which is available at
http://www.eclipse.org/legal/epl-2.0.

This Source Code may also be made available under the following Secondary
Licenses when the conditions for such availability set forth in the Eclipse
Public License, v. 2.0 are satisfied: GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or (at your
option) any later version, with the GNU Classpath Exception which is available
at https://www.gnu.org/software/classpath/license.html.
