# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  java8:
    docker:
      - image: circleci/clojure:openjdk-8-lein
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-java8-dependencies-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-java8-dependencies-{{ checksum "project.clj" }}
      - run: lein test-all

  java11:
    docker:
      - image: circleci/clojure:openjdk-11-lein
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-java11-dependencies-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-java11-dependencies-{{ checksum "project.clj" }}
      - run: lein test-all

workflows:
  version: 2
  all_test:
    jobs:
      - java8
      - java11
